version: '3.1'

networks:
  red:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - red
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    networks:
     - red
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_NUM_PARTITIONS: "2"

    ports:
      - 9092:9092

  miembros_producer:
    container_name: miembros_producer
    build: ./server/Producers/Miembros
    depends_on:
       - zookeeper
       - kafka 

    networks:
       - red
    ports:
      - "3000:3000"
        
  miembros_consumer:
    container_name: miembros_consumer
    build: ./server/Consumers/Miembros
    networks:
      - red
    depends_on:
       - zookeeper
       - kafka 
    ports:
      - "8000:8000"

  ventas_producer:
    container_name: ventas_producer
    build: ./server/Producers/Ventas
    networks:
      - red
    depends_on:
       - zookeeper
       - kafka
    ports:
      - "3001:3000"

  ventas_consumer:
    container_name: ventas_consumer
    build: ./server/Consumers/Ventas
    networks:
      - red
    depends_on:
       - zookeeper
       - kafka 
    ports:
      - "8001:8000"

  stock_consumer:
    container_name: stock_consumer
    build: ./server/Consumers/Stock
    networks:
      - red
    depends_on:
       - zookeeper
       - kafka 
    environment: 
      - kafka
    ports:
      - "8002:8000"

  ubicacion_producer:
    container_name: ubicacion_producer
    build: ./server/Producers/Ubicacion
    networks:
      - red
    depends_on:
       - zookeeper
       - kafka 
    ports:
      - "3002:3000"

  ubicacion_consumer:
    container_name: ubicacion_consumer
    build: ./server/Consumers/Ubicacion
    networks:
      - red
    depends_on:
       - zookeeper
       - kafka 
    ports:
      - "8003:8000"