version: "3.7"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092

  postgres:
    image: bitnami/postgresql:12.10.0
    container_name: postgres-tarea1
    volumes:
      #- ./Crawler/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tarea1
      - ALLOW_EMPTY_PASSWORD=yes



  Ventas:
    build:
      context: ./Ventas
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    volumes:
      - ./node/index.js:/app/index.js
    ports:
      - 3000:3000

  Miembros:
    build:
      context: ./Miembros
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3001
      kafkaHost: kafka:9092
    volumes:
      - ./node/index.js:/app/index.js
    ports:
      - 3001:3000


    